#!/bin/bash
set -e

echo "=== Building Docker cross-compile environment for mpv ==="
echo "    Building: freetype, fribidi, harfbuzz, libass, libxml2, OpenSSL, FFmpeg, mpv"
echo ""
docker build -t mpv-trimui-builder .

echo ""
echo "=== Collecting mpv binary and libraries ==="
rm -rf dist
mkdir -p dist/lib

docker run --rm --user "$(id -u):$(id -g)" -v "$(pwd)/dist":/dist mpv-trimui-builder /bin/bash -c '
    set -e
    PREFIX=/sdk/prefix

    cp $PREFIX/bin/mpv /dist/

    # Strip binary
    aarch64-linux-gnu-strip /dist/mpv 2>/dev/null || true

    # For each shared library in PREFIX, copy it as its SONAME (real file, not symlink).
    # FAT filesystem does not support symlinks; the dynamic linker needs the soname file.
    # Skip EGL/GLES: device has real PowerVR libs at /usr/lib64; our sysroot ones are stubs.
    for lib in $PREFIX/lib/*.so.*; do
        [ -f "$lib" ] || continue
        # Get SONAME from the library
        soname=$(aarch64-linux-gnu-objdump -p "$lib" 2>/dev/null | awk "/SONAME/{print \$2}")
        if [ -z "$soname" ]; then
            continue
        fi
        # Skip EGL/GLES: the device has the real PowerVR libraries. OpenSSL 3 is bundled
        # (libssl.so.3, libcrypto.so.3): the device only has 1.1.
        case "$soname" in
            libEGL*|libGLES*) continue ;;
        esac
        # Copy to soname name (overwrites if already present — last write wins for duplicates)
        cp "$lib" "/dist/lib/$soname"
        aarch64-linux-gnu-strip "/dist/lib/$soname" 2>/dev/null || true
    done

    # Allwinner Cedar H.264 decoder (libcedarc): unversioned .so files, not matched above.
    # Copied as they are: libVE.so was patched (fix-fini.py), the plugins are prebuilt.
    for lib in libvdecoder libMemAdapter libcdc_base libVE libvideoengine libcwrapper liblogwrapper libawh264; do
        cp $PREFIX/lib/$lib.so /dist/lib/
    done

    # Bundle CA certificates for HTTPS support
    cp /etc/ssl/certs/ca-certificates.crt /dist/ 2>/dev/null || true

    # Bundle DejaVu Sans font — fontconfig will find it via fonts.conf generated by launch.sh.
    mkdir -p /dist/fonts
    cp /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf /dist/fonts/ 2>/dev/null || \
    find /usr/share/fonts -name "*.ttf" | head -1 | xargs -I{} cp {} /dist/fonts/ 2>/dev/null || true

    echo "Done."
'

cp -f launch.sh dist/ 2>/dev/null || true
cp -f mpv.conf dist/ 2>/dev/null || true
# fontconfig and expat from the device's firmware (libass links them for font discovery)
cp -f syslibs/libfontconfig.so.1 dist/lib/
cp -f syslibs/libexpat.so.1 dist/lib/
chmod +x dist/launch.sh 2>/dev/null || true

echo ""
echo "=== Build complete ==="
file dist/mpv
ls -lh dist/mpv
echo ""
echo "Libraries:"
ls -lh dist/lib/
echo ""
echo "Deploy: scp -r dist/* root@<DEVICE_IP>:/mnt/SDCARD/Apps/mpv/"
