set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER /usr/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/aarch64-linux-gnu-g++)
set(CMAKE_AR /usr/bin/aarch64-linux-gnu-ar CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB /usr/bin/aarch64-linux-gnu-ranlib CACHE FILEPATH "" FORCE)
set(CMAKE_FIND_ROOT_PATH /sdk/prefix /sdk/usr)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_INSTALL_PREFIX /sdk/prefix)
set(CMAKE_PREFIX_PATH /sdk/prefix)
set(CMAKE_C_FLAGS "-I/sdk/prefix/include -I/sdk/usr/include -O2")
set(CMAKE_CXX_FLAGS "-I/sdk/prefix/include -I/sdk/usr/include -O2")
set(CMAKE_EXE_LINKER_FLAGS "-L/sdk/prefix/lib -L/sdk/usr/lib")
set(CMAKE_SHARED_LINKER_FLAGS "-L/sdk/prefix/lib -L/sdk/usr/lib")
